### ISSUE TITLE
The package is slowing down application booting time

### ISSUE THREAD

**Issue by tgeorgel** [codeat3/blade-phosphor-icons#18]
Hey there, I'm fighting with my Laravel app since a few days, as my app got way slower to boot (we are talking from 200ms to 3000ms to load a simple livewire page).

After diving in and disabling package discovery one by one, I found that this package was in cause.

Do you think there is a way to boost SVG loading performance, or is it simply because there are too much icons for my machine resources ? 

I've been trying to make use of blade cache, but it does seems to be helping. Thanks for you help!

**Comment by swapnilsarwe** [comment]
Have you tried using the following command
```
php artisan icons:cache
```

It should surely help with the performance.

Refer:
https://github.com/codeat3/blade-phosphor-icons#blade-icons
&&
https://github.com/blade-ui-kit/blade-icons#caching

**Comment by tgeorgel** [comment]
I totally not tried as I didn't see this, my bad!
Thanks for sharing, I'll give it a go ! :)

**Comment by swapnilsarwe** [comment]
> I totally not tried as I didn't see this, my bad!
> Thanks for sharing, I'll give it a go ! :) 

I will probably mention it as a section in my README clearly highlighting this.
