### ISSUE TITLE
Laravel 11 Support

### ISSUE THREAD

**Issue by waynelogic** [codeat3/blade-phosphor-icons#27]
The "2.0" constraint for "codeat3/blade-phosphor-icons" appears too strict and will likely not match what you want. See https://getcomposer.org/constraints                                                                                                                                                 
./composer.json has been updated
    - Root composer.json requires codeat3/blade-phosphor-icons 2.0 -> satisfiable by codeat3/blade-phosphor-icons[2.0.0].
    - codeat3/blade-phosphor-icons 2.0.0 requires illuminate/support ^8.0|^9.0|^10.0 -> found illuminate/support[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.4] but these were not loaded, likely because it conflicts with another require.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

There is an error when installing that package on Laravel 11. Will there be any support of 11 Lara version?

**Comment by swapnilsarwe** [comment]
@waynelogic 
we have already added support for laravel 11.
Kindly update your composer.json with
`"codeat3/blade-phosphor-icons": "^2.0"` and try. It should work for sure.

**Comment by swapnilsarwe** [comment]
> illuminate/support ^8.0|^9.0|^10.0 -> found illuminate/support[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.4] but these were not loaded, likely because it conflicts with another require.

If above does not work, additionallly you can do the following
i guess you have another dependency which is conflicting, you can try deleting composer.lock and try composer update.

**Comment by swapnilsarwe** [comment]
@waynelogic 
i am assuming that the above fix worked for you, hence closing this.
Feel free to re-open a new one - if it still exists.
